# Generated by Django 2.1.5 on 2019-02-13 08:54

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import hicquery.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiCQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='unique id of the hic view session')),
                ('title', models.CharField(max_length=500, verbose_name='title of the session')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create date')),
                ('bed_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/k/PrivateHub/hic3dviewer-web/backend/data-dev'), upload_to=hicquery.models.query_upload_path)),
                ('matrix_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/k/PrivateHub/hic3dviewer-web/backend/data-dev'), upload_to=hicquery.models.query_upload_path)),
                ('model_3d_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/k/PrivateHub/hic3dviewer-web/backend/data-dev'), upload_to=hicquery.models.query_upload_path)),
                ('linker_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/k/PrivateHub/hic3dviewer-web/backend/data-dev'), upload_to=hicquery.models.query_upload_path)),
            ],
        ),
    ]
